- hosts: all
  become: yes
  tasks:
  - name: Install Apache
    include: apache.yml
  - name: Install packages
    include: php.yml
  - name: Istall wordpress
    include: wordpress.yml
  - name: Install database
    include: db.yml